services:
  app:
    build:
      context: ..
    ports:
      - 8080:80
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./config.php:/var/www/phpipam/config.php:ro
  
  mariadb:
    image: mariadb:latest@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d
    environment:
      MARIADB_ROOT_PASSWORD: toor
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 120s
      interval: 5s
      timeout: 5s
      retries: 3
