services:
  app:
    build:
      context: ..
    ports:
      - 8080:80
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./config.php:/var/www/phpipam/config.php:ro
  
  mariadb:
    image: mariadb:latest@sha256:759869cb6f003234a95c6384cdee245b4bce7de26913fe607a8110362c0c007d
    environment:
      MARIADB_ROOT_PASSWORD: toor
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 120s
      interval: 5s
      timeout: 5s
      retries: 3
