services:
  app:
    build:
      context: ..
    ports:
      - 8080:80
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./config.php:/var/www/phpipam/config.php:ro
  
  mariadb:
    image: mariadb:latest@sha256:b3af559fc38e013c50dd5b5993bfbbb21125c1a62d976b3b0a14d9c4acaae578
    environment:
      MARIADB_ROOT_PASSWORD: toor
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 120s
      interval: 5s
      timeout: 5s
      retries: 3
