name: E2E Test

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - 'e2e/**'
      - '.github/workflows/e2e.yaml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - 'e2e/**'
      - '.github/workflows/e2e.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Docker
        uses: docker/setup-docker-action@77e84dbf09b47d1e29270283c22f16145aa85ca1 # v5
        with:
          version: latest

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@4eb059ff7f16592f9c84d5ca339c53cb7c5064e2 # v2
        with:
          version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6
        with:
          package_json_file: e2e/package.json

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: e2e/pnpm-lock.yaml

      - name: Start dev compose
        run: docker compose up --wait --build
        working-directory: e2e

      - name: Cypress run
        uses: cypress-io/github-action@4c06c48f3ffea349b7189aa06dfcda47a9fa7b92 # v7
        with:
          package-manager-cache: false
          working-directory: e2e
          wait-on: 'http://localhost:8080'
        env:
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
